const allGenere = [
    "Arte",
    "Aventura",
    "Autoayuda",
    "Biografía",
    "Ciencia",
    "Ciencia Ficción",
    "Cocina",
    "Cómic",
    "Crimen",
    "Distópico",
    "Ensayo",
    "Economía",
    "Fantasía",
    "Fantasía Épica",
    "Ficción Histórica",
    "Filosofía",
    "Humor",
    "Juvenil",
    "Manga",
    "Memorias",
    "Misterio",
    "No Ficción",
    "Novela Gráfica",
    "Oeste",
    "Poesía",
    "Política",
    "Religión",
    "Romance",
    "Sátira",
    "Suspenso",
    "Terror",
    "Teatro",
    "Viajes",
];

export {allGenere}